export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_CREDS = 'UPDATE_CREDS';
export const LOGOUT = 'LOGOUT';
export const COGNITO_INITIAL_SETUP = 'COGNITO_INITIAL_SETUP';

export const GET_CREDENTIALS_REQUEST = 'GET_CREDENTIALS_REQUEST';
export const GET_CREDENTIALS_SUCCESS = 'GET_CREDENTIALS_SUCCESS';
export const GET_CREDENTIALS_ERROR = 'GET_CREDENTIALS_ERROR';
